{% set version = '0.11.4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rayvertex
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rayvertex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rayvertex/rayvertex_{{ version }}.tar.gz
  sha256: 441ac38876302d9ed148bb6380aeb5d5d883be6826b2bb05391e0d71ce9e7075

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ stdlib('c') }}              # [not win]
    - {{ stdlib('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=1.0.6
    - r-rcppthread
    - r-cli
    - r-digest
    - r-pillar
    - r-png
    - r-rayimage >=0.11.0
    - r-spacefillr
    - r-tibble
    - r-vctrs
    - r-withr
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=1.0.6
    - r-rcppthread
    - r-cli
    - r-digest
    - r-pillar
    - r-png
    - r-rayimage >=0.11.0
    - r-spacefillr
    - r-tibble
    - r-vctrs
    - r-withr

test:
  commands:
    - $R -e "library('rayvertex')"           # [not win]
    - "\"%R%\" -e \"library('rayvertex')\""  # [win]

about:
  home: https://www.rayvertex.com, https://github.com/tylermorganwall/rayvertex
  license: GPL-3.0-or-later
  summary: Rasterize images using a 3D software renderer. 3D scenes are created either by importing
    external files, building scenes out of the included objects, or by constructing
    meshes manually. Supports point and directional lights, anti-aliased lines, shadow
    mapping, transparent objects, translucent objects, multiple materials types, reflection,
    refraction, environment maps, multicore rendering, bloom, tone-mapping, and screen-space
    ambient occlusion.
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r

# The original CRAN metadata for this package was:

# Package: rayvertex
# Type: Package
# Title: 3D Software Rasterizer
# Version: 0.11.4
# Date: 2024-07-10
# Authors@R: c(person("Tyler", "Morgan-Wall", email = "tylermw@gmail.com", role = c("aut", "cph", "cre"), comment = c(ORCID = "0000-0002-3131-3814")), person("Syoyo", "Fujita", role=c("ctb", "cph")), person("Vilya", "Harvey", role = c("ctb", "cph")), person("G-Truc Creation", role = c("ctb", "cph")), person("Sean", "Barrett", role = c("ctb", "cph")))
# Maintainer: Tyler Morgan-Wall <tylermw@gmail.com>
# Description: Rasterize images using a 3D software renderer. 3D scenes are created either by importing external files, building scenes out of the included objects, or by constructing meshes manually. Supports point and directional lights, anti-aliased lines, shadow mapping, transparent objects, translucent objects, multiple materials types, reflection, refraction, environment maps, multicore rendering, bloom, tone-mapping, and screen-space ambient occlusion.
# License: GPL (>= 3)
# Copyright: file inst/COPYRIGHTS
# Depends: R (>= 4.1)
# Imports: Rcpp (>= 1.0.6), grDevices, rayimage (>= 0.11.0), png, digest, pillar, vctrs, tibble, withr, cli
# Suggests: Rvcg, magick, raster, testthat (>= 3.0.0)
# LinkingTo: Rcpp, spacefillr, RcppThread, rayimage
# RoxygenNote: 7.3.1
# URL: https://www.rayvertex.com, https://github.com/tylermorganwall/rayvertex
# BugReports: https://github.com/tylermorganwall/rayvertex/issues
# Encoding: UTF-8
# SystemRequirements: C++17
# Config/testthat/edition: 3
# NeedsCompilation: yes
# Packaged: 2024-07-22 03:09:11 UTC; tyler
# Author: Tyler Morgan-Wall [aut, cph, cre] (<https://orcid.org/0000-0002-3131-3814>), Syoyo Fujita [ctb, cph], Vilya Harvey [ctb, cph], G-Truc Creation [ctb, cph], Sean Barrett [ctb, cph]
# Repository: CRAN
# Date/Publication: 2024-07-22 04:30:02 UTC
